# Redis configuration with password authentication
# https://redis.io/topics/config

bind 0.0.0.0
protected-mode yes
port 6379

# Require clients to issue AUTH <PASSWORD> before processing any other commands.
requirepass mystrongpassword

# Save data to disk every 900 seconds if at least 1 key changed
save 900 1
save 300 10
save 60 10000

# Append only file for durability
appendonly yes
